apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-canary
  namespace: ge-go-greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      version: canary
  template:
    metadata:
      labels:
        app: go-app
        version: canary
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: go-app
          image: ghcr.io/jmirandasq/ge-go-greeter:sha-40e1a0e
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
