apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: go-app-public
  namespace: ge-go-greeter
spec:
  parentRefs:
    - name: go-app-gateway
      namespace: ge-go-greeter
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: go-app-stable
          port: 80
          weight: 80
        - name: go-app-canary
          port: 80
          weight: 20
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: go-app
  namespace: ge-go-greeter
spec:
  parentRefs:
    - name: go-app-gateway
      namespace: ge-go-greeter
  rules:
    - matches:
        - headers:
            - name: X-Version
              value: abtest
          path:
            type: PathPrefix
            value: /greet
      backendRefs:
        - name: go-app-canary
          port: 80
          weight: 100

    - matches:
        - path:
            type: PathPrefix
            value: /greet
      backendRefs:
        - name: go-app-stable
          port: 80
          weight: 80
        - name: go-app-canary
          port: 80
          weight: 20
