grafana:
  enabled: true
  service:
    type: NodePort
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy
      isDefault: false
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: "fake"
    - name: Tempo
      type: tempo
      url: http://tempo.monitoring.svc.cluster.local:3200
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

alertmanager:
  enabled: false
